templates:
  optimize-script:
    name: "Optimize Bash Script"
    description: "Profile & optimize bash script performance"
    prompt: |
      Optimize this bash script for performance:

      Current issues:
      - [describe bottleneck if known]

      Requirements:
      - Profile & identify bottlenecks
      - Use modern tools (fd, rg, parallel) w/ fallbacks
      - Minimize subprocesses & I/O
      - Batch operations where possible
      - Show before/after metrics

      File: {file_path}
    variables:
    - file_path

  add-error-handling:
    name: "Add Error Handling"
    description: "Implement comprehensive error handling"
    prompt: |
      Add robust error handling to this script:

      Requirements:
      - set -euo pipefail
      - trap cleanup EXIT ERR
      - Validate inputs
      - Check command availability (has function)
      - Meaningful error messages
      - Exit codes (0=success, 1=error, 2=usage)

      File: {file_path}
    variables:
    - file_path

  make-distro-agnostic:
    name: "Distro-Agnostic Script"
    description: "Support multiple Linux distributions"
    prompt: |
      Make this script work across distributions:

      Requirements:
      - Detect pkg mgr: paru→yay→pacman (Arch) | apt (Debian)
      - Check installed packages before installing
      - Provide distro-specific hints in comments
      - Handle path differences (XDG, /usr/local, etc)
      - Test on: Arch, Debian/Ubuntu

      File: {file_path}
    variables:
    - file_path

  add-interactive-mode:
    name: "Add Interactive Mode"
    description: "Add fzf-based interactive selection"
    prompt: |
      Add interactive mode using fzf:

      Requirements:
      - Trigger when required args missing
      - Use fd/find for file selection
      - Use rg/grep for content search
      - Fallback if fzf unavailable
      - Show preview pane where useful

      File: {file_path}
      Selection type: {selection_type}
    variables:
    - file_path
    - selection_type

  security-audit:
    name: "Security Audit"
    description: "Audit script for security issues"
    prompt: |
      Security audit this script:

      Check for:
      - [ ] Input validation (all external data)
      - [ ] Command injection (unquoted vars, eval)
      - [ ] Path traversal
      - [ ] Privilege escalation
      - [ ] Hardcoded secrets
      - [ ] Temp file security
      - [ ] Information disclosure in errors

      File: {file_path}

      Provide: Risk level + Fix for each issue
    variables:
    - file_path

  write-tests:
    name: "Write Tests"
    description: "Generate test suite"
    prompt: |
      Write tests for this script:

      Test framework: {test_framework}

      Coverage:
      - Happy path
      - Error conditions
      - Edge cases
      - Input validation
      - Mock external commands

      File: {file_path}
    variables:
    - file_path
    - test_framework

  generate-readme:
    name: "Generate README"
    description: "Create comprehensive README"
    prompt: |
      Generate README for this script/project:

      Include:
      - Brief description
      - Features list
      - Installation (Arch/Debian)
      - Usage examples
      - Configuration options
      - Troubleshooting
      - Contributing guidelines

      Project: {project_path}
      Style: Concise, scannable, examples-heavy
    variables:
    - project_path

  modernize-tools:
    name: "Modernize Tools"
    description: "Replace traditional tools with modern alternatives"
    prompt: |
      Modernize this script with faster tools:

      Replacements:
      - find → fd (w/ fallback)
      - grep → rg (w/ fallback)
      - cat → bat (w/ fallback)
      - sed → sd (w/ fallback)
      - curl/wget → aria2 (no pipe) → curl → wget
      - xargs → parallel → rust-parallel

      Keep fallbacks for compatibility.

      File: {file_path}
    variables:
    - file_path

  add-dry-run:
    name: "Add Dry-Run Mode"
    description: "Implement safe preview mode"
    prompt: |
      Add dry-run mode to this script:

      Requirements:
      - Flag: -d, --dry-run
      - Echo commands instead of executing
      - Show what would change
      - Validate inputs even in dry-run
      - Clear visual distinction (color)

      File: {file_path}
    variables:
    - file_path

  parallel-processing:
    name: "Add Parallel Processing"
    description: "Implement concurrent execution"
    prompt: |
      Add parallel processing to this script:

      Requirements:
      - Use rust-parallel → parallel → xargs
      - Configurable job count (-j flag)
      - Progress indication
      - Error aggregation
      - Maintain order if needed

      Operation to parallelize: {operation}
      File: {file_path}
    variables:
    - file_path
    - operation
