# This file configures https://pre-commit.com/
# to use specific hooks and options.

fail_fast: false

repos:
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2  # use the shfmt version you want
    hooks:
      - id: shfmt
        args: [ -i, "2", -kp, -bn ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        args: [ --allow-multiple-documents ]
    -   id: check-toml
    -   id: check-xml
    -   id: pretty-format-json
    -   args: [ --autofix ]
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-symlinks
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: check-added-large-files

-   repo: https://github.com/anordal/shellharden
    rev: v4.4.1
    hooks:
      - id: shellharden
        #args: [ --transform ]

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
      - id: git-check  # Configure in .gitattributes
      - id: git-dirty  # Configure in .gitignore
      #- id: markdownlint # Configure in .mdlrc
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shellcheck
        args: [ --external-sources ]
      
