#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob

# Config
QUERY="${GH_MERGE_QUERY:-author:app/dependabot}"
LIMIT="${GH_MERGE_LIMIT:-50}"
BRANCH="${GH_MERGE_BRANCH:-combined-deps}"
TITLE="${GH_MERGE_TITLE:-chore(deps): combined dependency updates}"

die(){ printf '%s\n' "$1" >&2; exit 1; }
log(){ printf ':: %s\n' "$@" >&2; }

usage(){
  cat <<EOF
Usage: ${0##*/} [OPTIONS]

Combine multiple PRs into one clean squashed PR.

Options:
  -q, --query QUERY    PR search query (default: "$QUERY")
  -n, --limit N        Max PRs (default: $LIMIT)
  -b, --branch NAME    Branch name (default: $BRANCH)
  -t, --title TITLE    PR title
  --prs N1,N2,...      Specific PR numbers
  --skip-checks        Ignore failing checks
  --dry-run            Show what would be done
  -h, --help           Show this help
EOF
}

main(){
  local prs="" skip_checks=false dry_run=false
  while [[ $# -gt 0 ]]; do
    case $1 in
      -h|--help) usage; exit 0;;
      -q|--query) QUERY=$2; shift 2;;
      -n|--limit) LIMIT=$2; shift 2;;
      -b|--branch) BRANCH=$2; shift 2;;
      -t|--title) TITLE=$2; shift 2;;
      --prs) prs=$2; shift 2;;
      --skip-checks) skip_checks=true; shift;;
      --dry-run) dry_run=true; shift;;
      *) die "Unknown: $1";;
    esac
  done

  command -v gh &>/dev/null || die "gh CLI required"
  git rev-parse --git-dir &>/dev/null || die "Not a git repo"

  local base
  base=$(gh repo view --json defaultBranchRef -q .defaultBranchRef.name)
  log "Base branch: $base"

  # Build jq filter for specific PRs
  local jq_filter='.[] | select(.mergeable == "MERGEABLE")'
  [[ -n $prs ]] && jq_filter=".[] | select(.number | IN(${prs//,/,}))"

  # Fetch eligible PRs
  local -a pr_data
  mapfile -t pr_data < <(
    gh pr list --search "$QUERY" --limit "$LIMIT" \
      --json number,headRefName,title,author \
      --jq "$jq_filter | [.number, .headRefName, .title, .author.login] | @tsv"
  )
  [[ ${#pr_data[@]} -eq 0 ]] && die "No eligible PRs found"

  log "Found ${#pr_data[@]} PRs:"
  printf '  %s\n' "${pr_data[@]}" >&2

  if [[ $dry_run == true ]]; then
    log "[dry-run] Would combine ${#pr_data[@]} PRs into $BRANCH"
    return 0
  fi

  # Prep workspace
  git fetch --all --prune -q
  git checkout -q "$base"
  git pull --ff-only -q
  git branch -D "$BRANCH" 2>/dev/null || true
  git checkout -q -b "$BRANCH"

  # Process each PR
  local body="" count=0 merged=()
  local num ref title author
  for line in "${pr_data[@]}"; do
    IFS=$'\t' read -r num ref title author <<<"$line"

    # Check status unless skipped
    if [[ $skip_checks == false ]]; then
      if ! gh pr checks "$num" --fail-fast 2>/dev/null; then
        log "⊘ #$num checks failing, skip"
        continue
      fi
    fi

    log "→ Cherry-picking #$num ($ref)..."
    
    # Get merge-base and cherry-pick range
    local merge_base
    merge_base=$(git merge-base "origin/$base" "origin/$ref" 2>/dev/null) || {
      log "⊘ #$num no common ancestor, skip"
      continue
    }

    if ! git cherry-pick --no-commit "$merge_base..origin/$ref" 2>/dev/null; then
      log "⊘ #$num conflict, skip"
      git cherry-pick --abort 2>/dev/null || git reset --hard HEAD
      continue
    fi

    # Stage and commit with fixup marker for autosquash
    if [[ -n $(git diff --cached --name-only) ]]; then
      git commit -q -m "fixup! $TITLE" -m "PR #$num: $title @$author"
      merged+=("$num")
      body+=$'\n'"- $title (#$num) @$author"
      ((++count))
      log "✓ #$num merged"
    else
      log "⊘ #$num no changes"
    fi
  done

  [[ $count -eq 0 ]] && die "No PRs merged"

  # Squash all commits
  log "Squashing $count commits..."
  git reset --soft "$base"
  git commit -m "$TITLE" -m "Combined PRs:$body"

  # Push and create PR
  log "Pushing $BRANCH..."
  git push -f -u origin "$BRANCH"

  local pr_body
  pr_body=$(cat <<EOF
Combined dependency updates into single PR.

## Merged PRs
$body

---
<sub>Auto-generated by gh-merge-prs</sub>
EOF
)

  gh pr create \
    --title "$TITLE" \
    --body "$pr_body" \
    --label dependencies \
    --base "$base" \
    --head "$BRANCH"

  log "✓ Created combined PR with $count updates"
  log "  Merged: ${merged[*]}"
}

main "$@"
