#!/usr/bin/env bash
set -Eeuo pipefail
shopt -s nullglob globstar extglob dotglob
IFS=$'\n\t'
export LC_ALL=C LANG=C

# Colors (trans palette)
LBLU=$'\e[38;5;117m' PNK=$'\e[38;5;218m' BWHT=$'\e[97m'
YLW=$'\e[33m' RED=$'\e[31m' GRN=$'\e[32m' DEF=$'\e[0m' BLD=$'\e[1m'

has(){ command -v "$1" &>/dev/null; }
log(){ printf "${LBLU}:: %s${DEF}\n" "$*" >&2; }
warn(){ printf "${YLW}⚠ %s${DEF}\n" "$*" >&2; }
err(){ printf "${RED}ERROR: %s${DEF}\n" "$*" >&2; }
die(){ err "$*"; exit 1; }
success(){ printf "${GRN}✓ %s${DEF}\n" "$*" >&2; }

# Config (override via env)
QUERY=${GH_MERGE_QUERY:-author:app/dependabot}
LIMIT=${GH_MERGE_LIMIT:-50}
BRANCH=${GH_MERGE_BRANCH:-combined-deps}
TITLE=${GH_MERGE_TITLE:-chore(deps): combined dependency updates}

usage(){
  cat <<EOF
Usage: ${0##*/} [OPTIONS]

Combine multiple PRs into one clean squashed PR.

Options:
  -q, --query QUERY    PR search query (default: "$QUERY")
  -n, --limit N        Max PRs to evaluate (default: $LIMIT)
  -b, --branch NAME    Target branch name (default: $BRANCH)
  -t, --title TITLE    PR title (default: "$TITLE")
  --prs N1,N2,...      Combine only these specific PR numbers
  --skip-checks        Ignore failing CI checks
  --dry-run            Show what would be done without making changes
  -h, --help           Show this help
  --version            Show version
EOF
}

main(){
  local prs="" skip_checks=false dry_run=false

  while (( $# )); do
    case $1 in
      -h|--help)    usage; exit 0;;
      --version)    printf 'gh-auto-merge 2.0.0\n'; exit 0;;
      -q|--query)   QUERY=${2:?missing query}; shift 2;;
      -n|--limit)   LIMIT=${2:?missing limit}; shift 2;;
      -b|--branch)  BRANCH=${2:?missing branch}; shift 2;;
      -t|--title)   TITLE=${2:?missing title}; shift 2;;
      --prs)        prs=${2:?missing PR numbers}; shift 2;;
      --skip-checks) skip_checks=true; shift;;
      --dry-run)    dry_run=true; shift;;
      *) die "Unknown option: $1. Use -h for help.";;
    esac
  done

  has gh  || die "gh CLI required"
  has git || die "git required"
  git rev-parse --git-dir &>/dev/null || die "Not a git repository"

  local base
  base=$(gh repo view --json defaultBranchRef -q .defaultBranchRef.name)
  log "Base branch: $base"

  # Build jq filter: all mergeable PRs, or a specific set by number
  local jq_filter='.[] | select(.mergeable == "MERGEABLE")'
  if [[ -n $prs ]]; then
    jq_filter=".[] | select(.number | IN(${prs}))"
  fi

  local -a pr_data
  mapfile -t pr_data < <(
    gh pr list --search "$QUERY" --limit "$LIMIT" \
      --json number,headRefName,title,author,mergeable \
      --jq "$jq_filter | [.number, .headRefName, .title, .author.login] | @tsv"
  )
  (( ${#pr_data[@]} > 0 )) || die "No eligible PRs found"

  log "Found ${#pr_data[@]} eligible PR(s):"
  printf '  %s\n' "${pr_data[@]}" >&2

  if [[ $dry_run == true ]]; then
    log "[dry-run] Would combine ${#pr_data[@]} PR(s) into $BRANCH"
    return 0
  fi

  # Prepare workspace: delete existing branch if present
  git fetch --all --prune -q
  git checkout -q "$base"
  git pull --ff-only -q
  git branch -D "$BRANCH" 2>/dev/null || :
  git checkout -q -b "$BRANCH"

  local body="" count=0 num ref title author merge_base
  local -a merged=()

  for line in "${pr_data[@]}"; do
    IFS=$'\t' read -r num ref title author <<<"$line"

    if [[ $skip_checks == false ]]; then
      if ! gh pr checks "$num" --fail-fast 2>/dev/null; then
        log "⊘ #$num: checks failing — skipping"
        continue
      fi
    fi

    log "Cherry-picking #$num ($ref)..."
    merge_base=$(git merge-base "origin/$base" "origin/$ref" 2>/dev/null) || {
      log "⊘ #$num: no common ancestor — skipping"
      continue
    }

    if ! git cherry-pick --no-commit "$merge_base..origin/$ref" 2>/dev/null; then
      log "⊘ #$num: conflict — skipping"
      git cherry-pick --abort 2>/dev/null || git reset --hard HEAD
      continue
    fi

    if [[ -n $(git diff --cached --name-only) ]]; then
      git commit -q -m "fixup! $TITLE" -m "PR #$num: $title @$author"
      merged+=("$num")
      body+=$'\n'"- $title (#$num) @$author"
      (( ++count ))
      success "#$num merged"
    else
      log "⊘ #$num: no net changes — skipping"
    fi
  done

  (( count > 0 )) || die "No PRs could be merged"

  # Squash all fixup commits into one
  log "Squashing $count commit(s)..."
  git reset --soft "origin/$base"
  git commit -m "$TITLE" -m "Combined PRs:$body"

  # Force-push is required: this branch may have been pushed before
  log "Pushing $BRANCH..."
  git push --force-with-lease -u origin "$BRANCH"

  local pr_body
  pr_body=$(printf 'Combined dependency updates into a single PR.\n\n## Merged PRs\n%s\n\n---\n<sub>Auto-generated by gh-auto-merge</sub>\n' "$body")

  # Create label if it doesn't exist yet (ignore error if unsupported)
  gh label create dependencies --color 0075ca --description "Dependency updates" 2>/dev/null || :

  gh pr create \
    --title "$TITLE" \
    --body "$pr_body" \
    --label dependencies \
    --base "$base" \
    --head "$BRANCH"

  success "Created combined PR with $count update(s)"
  log "Merged PRs: ${merged[*]}"
}

main "$@"
