export NO_COLOR=1
export DBUS_SESSION_BUS_ADDRESS=no ZSTD_NBTHREADS=0
export LC_ALL=C LANG='C.UTF-8' LANGUAGE='en_US:en:C' LC_COLLATE=C LC_CTYPE=C
export GPG_TTY="$(tty)" TZ="Europe/Berlin"
export PYTHONOPTIMIZE=2 PYTHON_JIT=1 PYENV_VIRTUALENV_DISABLE_PROMPT=1
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}" \
       XDG_DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}" \
       XDG_STATE_HOME="${XDG_STATE_HOME:=$HOME/.local/state}" \
       XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
export MALLOC_CONF="metadata_thp:auto,tcache:true,background_thread:true,percpu_arena:percpu,trust_madvise:enabled"
export _RJEM_MALLOC_CONF="$MALLOC_CONF" MIMALLOC_VERBOSE=0 MIMALLOC_SHOW_ERRORS=0 MIMALLOC_SHOW_STATS=0 MIMALLOC_ALLOW_LARGE_OS_PAGES=1 MIMALLOC_PURGE_DELAY=25 MIMALLOC_ARENA_EAGER_COMMIT=2
