export NO_COLOR=1
export DBUS_SESSION_BUS_ADDRESS=no ZSTD_NBTHREADS=0
export LC_ALL=C LANG='C.UTF-8' LANGUAGE='en_US:en:C' LC_COLLATE=C LC_CTYPE=C
export GPG_TTY="$(tty)" TZ="Europe/Berlin"
export PYTHONOPTIMIZE=2 PYTHON_JIT=1 PYENV_VIRTUALENV_DISABLE_PROMPT=1
