#!/usr/bin/env bash
set -euo pipefail; IFS=$'\n\t'; shopt -s nullglob globstar
LC_COLLATE=C LC_CTYPE=C LANG=C.UTF-8

# https://gist.github.com/denji/52b9b0980ef3dadde0ff3d3ccf74a2a6
__GL_YIELD=1
__GL_THREADED_OPTIMIZATIONS=1
MESA_NO_ERROR=1
MESA_DEBUG=1
__GL_SHADER_DISK_CACHE=1
__GL_SORT_FBCONFIGS=1
__GL_WRITE_TEXT_SECTION=1

__NV_PRIME_RENDER_OFFLOAD=1
__GL_ALLOW_UNOFFICIAL_PROTOCOL=1
__GL_IGNORE_GLSL_EXT_REQS=1

QT_ENABLE_HIGHDPI_SCALING=1
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# https://gist.github.com/mvandermeulen/f65ccdc621437540c3b35f89ea915d03
__NV_USE_PAGE_ATTRIBUTE_TABLE=1
__NV_ENABLE_PCIE_GEN3=1
__NV_INITIALIZE_SYSTEM_MEMORY_ALLOCATIONS=0
__NV_ENABLE_STREAM_MEMOPS=1

export COLORTERM=truecolor
export SUDO_EDITOR="$EDITOR"

# https://github.com/YurinDoctrine/ultra-gaming-setup-wizard
MALLOC_CHECK=0
MALLOC_TRACE=0
LLVM_DEBUG=0
PP_DEBUG=0
LIBGL_DEBUG=0
GPU_USE_SYNC_OBJECTS=1
WINE_LARGE_ADDRESS_AWARE=1
WINEFSYNC=1
WINEFSYNC_FUTEX2=1
STAGING_WRITECOPY=1
PROTON_LOG=0
PROTON_FORCE_LARGE_ADDRESS_AWARE=1
PROTON_USE_WINED3D=0
PROTON_NO_ESYNC=1
PROTON_USE_FSYNC=1
PROTON_HIDE_NVIDIA_GPU=0
PROTON_ENABLE_NGX_UPDATER=1
PROTON_ENABLE_NVAPI=1
ENABLE_VKBASALT=1
DXVK_ASYNC=1
DXVK_SPIRV_OPT=ON
DXVK_SHADER_OPTIMIZE=1
DXVK_DEBUG_LAYERS=0
DXVK_LOG_LEVEL=none
MESA_DEBUG=0
MESA_NO_DITHER=1
MESA_NO_ERROR=1
MESA_SHADER_CACHE_DISABLE=false
mesa_glthread=true
ANV_ENABLE_PIPELINE_CACHE=1
NVIDIA_DEBUG=0
NVD_BACKEND=direct
NVD_LOG=0
__GL_THREADED_OPTIMIZATION=1
__GL_SYNC_TO_VBLANK=1
__GL_MaxFramesAllowed=1
__GL_SHADER_DISK_CACHE=1
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
USE_HEAP=1
GAMEMODE=1
