#!/usr/bin/env bash
set -euo pipefail; IFS=$'\n\t'; shopt -s nullglob globstar
LC_COLLATE=C LC_CTYPE=C LANG=C.UTF-8

# https://gist.github.com/denji/52b9b0980ef3dadde0ff3d3ccf74a2a6
__GL_YIELD=1
__GL_THREADED_OPTIMIZATIONS=1
MESA_NO_ERROR=1
MESA_DEBUG=1
__GL_SHADER_DISK_CACHE=1
__GL_SORT_FBCONFIGS=1
__GL_WRITE_TEXT_SECTION=1

__NV_PRIME_RENDER_OFFLOAD=1
__GL_ALLOW_UNOFFICIAL_PROTOCOL=1
__GL_IGNORE_GLSL_EXT_REQS=1

QT_ENABLE_HIGHDPI_SCALING=1
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# https://gist.github.com/mvandermeulen/f65ccdc621437540c3b35f89ea915d03
__NV_USE_PAGE_ATTRIBUTE_TABLE=1
__NV_ENABLE_PCIE_GEN3=1
__NV_INITIALIZE_SYSTEM_MEMORY_ALLOCATIONS=0
__NV_ENABLE_STREAM_MEMOPS=1

export COLORTERM=truecolor
export SUDO_EDITOR="$EDITOR"
