#!/bin/bash

# Description: Script to allow users to switch to CLI or GUI mode
# Usage: flipui [-d] [gui]/[cli]
#	 - The [-d] means: set mode as 'default' during boot - OPTIONAL

# Used for checking which mode is currently active
isGUI_active=$(systemctl is-active graphical.target); # returns either 'active' or 'inactive'

# Value meanings:
#   - Inactive : CLI mode
#   - Active   : GUI mode

#echo "GUI status:" $isGUI_active;

#args=$*; # store all arguments passed
#echo $args;
echo "";

# Show current default mode for boot
defaultMode="Current default boot mode is set to:";

if [[ $(systemctl get-default) == 'graphical.target' ]]
then
	defaultMode+=' Graphical Interface';
else
	defaultMode+=' Command Line Interface';
fi

echo $defaultMode;
echo "";

# Check for arguments passed
if [[ $# -eq 1 ]]
then
	# CLI mode -> GUI mode
	if [[ $1 == 'cli' ]]
	then
		if [[ $isGUI_active == 'inactive' ]]
		then
			echo "You are already in CLI mode...!";
		else
			#$(sudo systemctl isolate multi-user.target); # switch to terminal mode if GUI is active
			echo "";
			echo "!!! IMPORTANT WARNING !!!";
			echo "Switching to CLI mode from GUI mode will result in a BLANK SCREEN...!";
			echo "";
			echo "* To set default mode during boot run:";
			echo "	flipui -d gui";
			echo "	reboot";
			echo "";
			echo "* To temporarily switch to CLI mode, use the following keyboard shortcut:";
			echo "	ctrl + alt + F[1-6] (try from 1 to 6 and see which one works)";
			echo "";
			echo "* To return back to desktop after using the previous keyboard shortcut, use:";
			echo "	ctrl + alt + F7";
		fi
		
	# GUI mode -> CLI mode
	elif [[ $1 == 'gui' ]]
	then
		if [[ $isGUI_active == 'active' ]]
		then
			echo "You are already in GUI mode...!";
		else
			$(sudo systemctl isolate graphical.target); # switch to desktop mode if CLI is active
		fi
	fi
	
elif [[ $# -eq 2 ]]
then
	# Check if argument [-d] is provided
	if [[ $1 == '-d' ]]
	then
		if [[ $2 == 'cli' ]]
		then
			$(sudo systemctl set-default multi-user.target); # set default mode to terminal mode during boot
			echo "Success: The next time your system reboots, you'll be using the CLI...";
			
		elif [[ $2 == 'gui' ]]
		then
			$(sudo systemctl set-default graphical.target); # set default mode to desktop mode during boot
			echo "Success: The next time your system reboots, you'll be using the GUI...";
			
		else
			echo "Usage: flipui [-d] gui/cli";
			echo "	- The [-d] means: set mode as 'default' during boot - OPTIONAL";
		fi
	else
		echo "Usage: flipui [-d] gui/cli";
		echo "	- The [-d] means: set mode as 'default' during boot - OPTIONAL";
	fi
else
	#echo "Please pass either 'gui' or 'cli' as parameters...";
	#echo "Optional argument: [-d] for setting as default.";
	echo "Usage: flipui [-d] gui/cli";
	echo "	- The [-d] means: set mode as 'default' during boot - OPTIONAL";
fi

echo "";
