export HISTCONTROL=ignoreboth

alias ssh='dbclient'
alias ptch='patch -p1 <'
alias cleansh='curl-rustls -fsSL https://raw.githubusercontent.com/Ven0m0/Linux-OS/refs/heads/main/Cachyos/Clean.sh | sudo bash'
alias updatesh='curl-rustls -fsSL https://raw.githubusercontent.com/Ven0m0/Linux-OS/refs/heads/main/Cachyos/Updates.sh | sudo bash'

alias ls='eza -al --color=always --group-directories-first --icons' # preferred listing
alias la='eza -a --color=always --group-directories-first --icons'  # all files and dirs
alias ll='eza -l --color=always --group-directories-first --icons'  # long format
alias lt='eza -aT --color=always --group-directories-first --icons' # tree listing
alias l.="eza -a | grep -e '^\.'"                                   # show only dotfiles
alias rg='rg --color=auto'
alias grep='rg -uuu --color=auto'
alias fgrep='rg -uuu -F --color=auto'
alias egrep='rg -E --color=auto'
alias sudo='doas'
