#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc
. "$HOME/.cargo/env"

# Source ~/.bashrc for login shells
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# NON-INTERACTIVE OR LOGIN-ONLY SETTINGS BELOW
export LANG=C
export LC_ALL=C
