newline_style="Unix"
color="auto"
unstable_features = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
condense_wildcard_suffixes = true
wrap_comments = true
reorder_impl_items = true
