# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Only show the current directory
#format = """$directory$character"""

format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break$character"""

right_format = ""
# right_format = "$custom"

# Don’t add a blank line above the prompt
add_newline = false

scan_timeout = 10

# Customize the prompt symbol
[character]
success_symbol = '[➜](bold green)'

[directory]
style = "purple"
truncate_to_repo = true
truncation_symbol = '…/'

[username]
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
disabled = true
use_git_executable = false
ignore_submodules = false

[line_break]
disabled = false

[git_branch]
disabled = false

# https://github.com/fwdekker/mommy
[custom.mommy]
disabled = true
shell = ["fish", "-N"]
command = "mommy -1 -s $status"
when = "true"
