# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---

# Disabled certain linters due to duplication and or redundancy.
DISABLE_LINTERS: REPOSITORY_KICS, REPOSITORY_GRYPE, SPELL_VALE, SPELL_PROSELINT

DISABLE_ERRORS_LINTERS: SPELL_CSPELL, SPELL_LYCHEE, BASH_EXEC, BASH_SHFMT, BASH_SHELLCHECK, YAML_YAMLLINT, YAML_V8R, YAML_PRETTIER, REPOSITORY_SEMGREP, REPOSITORY_GRYPE, REPOSITORY_DEVSKIM, PYTHON_BANDIT

ENABLE: BASH, MAKEFILE, POWERSHELL, PYTHON, CSS, ENV, HTML, JSON, MARKDOWN, XML, YAML, ACTION, DOCKERFILE, EDITORCONFIG, REPOSITORY, SPELL

SPELL_LYCHEE_DISABLE_ERRORS: true
YAML_V8R_FILE_EXTENSIONS: [".yml", ".yaml", ".toml", ".json", ".jsonc"]
YAML_V8R_DISABLE_ERRORS: true
YAML_YAMLLINT_DISABLE_ERRORS: true
YAML_PRETTIER_DISABLE_ERRORS: true
IGNORE_GENERATED_FILES: true
IGNORE_GITIGNORED_FILES: true
PARALLEL: true
PYTHON_DEFAULT_STYLE: ruff
SHOW_ELAPSED_TIME: true
REPORT_OUTPUT_FOLDER: megalinter-reports
FILTER_REGEX_EXCLUDE: '(\.github/workflows)'
