hide-mouse-cursor-when-typing = false
# working-dir = "$HOME"
#env-vars = []
use-fork = true
confirm-before-quit = true

[cursor]
blinking = false

[editor]
program = "micro"
args = []

[window]
opacity = 1.0
blur = false
decorations = "enabled"
mode = "Windowed"

[renderer]
performance = "High"
#backend = "Automatic"
backend = "Vulkan"
disable-unfocused-render = false
disable-occluded-render = true
target-fps = 120
strategy = "events"

[keyboard]
use-kitty-keyboard-protocol = true
ime-cursor-positioning = true
disable-ctlseqs-alt = false

[fonts]
hinting = true
disable-warnings-not-found = true

[scroll]
multiplier = 3.0
divider = 1.0

# [shell]
# program = "/bin/fish"
# args = ["--login"]

[navigation]
mode = "bookmark"
clickable = true
hide-if-single = true
use-split = true
# use-current-path = false

[developer]
log-level = "OFF"
enable-log-file = false
