# Sample Config file, works with toml and yaml
# Place in either:
#   ~/.config/dust/config.toml
#   ~/.dust.toml

# Print tree upside down (biggest highest)
reverse=false

# Subdirectories will not have their path shortened
display-full-paths=false

# Use file length instead of blocks
display-apparent-size=false

# No colors will be printed
no-colors=false

# No percent bars or percentages will be displayed
no-bars=true

# No total row will be displayed
skip-total=false

# Do not display hidden files
ignore-hidden=true

# print sizes in powers of 1000 (e.g., 1.1G)
#output-format="si"
