name: Validate Config Files Action
on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * 0"}]
  #push
  
jobs:
  build:
    name: validate-config-files
    runs-on: ubuntu-latest
    steps:
      - name: Validate Config Files Action
      - uses: kehoe/validate-configs-action@v4.0.1
