name: ShellCheck (manual)
on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  shellcheck:
    name: ShellCheck on-demand
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Run ShellCheck via Reviewdog
        uses: reviewdog/action-shellcheck@v1.32.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          path: "."
          pattern: |
            *.sh
            *.bash
            .bashrc
            bash_*
          exclude: |
            */.git/*
            ./.cache/*
            ./Linux-Settings/*
          check_all_files_with_shebangs: true
          shellcheck_flags: "-x -a -s bash"
