name: "Code lint"
permissions: {}
on: [push, pull_request, workflow_dispatch]
  
jobs:
  shellchecker:
    name: "ShellChecker"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
      - name: "ShellChecker"
        uses: a5k-actions/shellchecker@v0
