name: Reviewdog
#on: [push, pull_request, workflow_dispatch]
on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * 0"}]
  push:
    paths:
      - '**/*.sh'
      - '**/*.bash'
      - '.bashrc'
      - '.profile'
  pull_request:
    paths:
      - '**/*.sh'
      - '**/*.bash'
      - '.bashrc'
      - '.profile'
permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run ShellCheck via Reviewdog
        uses: reviewdog/action-shellcheck@v1.32.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          path: "."
          pattern: |
            "*.sh"
            "*.bash"
            ".bashrc"
            "bash_*"
            ".profile"
          #exclude: ".git/*"
          exclude: |
            */.git/*
            ./.cache/*
            ./Linux-Settings
          check_all_files_with_shebangs: "true"
          shellcheck_flags: "-x -s bash"
