name: Linter
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    permissions:
      packages: read
      statuses: write
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Determine Super-Linter version dynamically
      - name: Get Super-Linter version
        id: sl-version
        run: |
          version=$(echo "v8.1.0" | sed 's/^v//') # update manually or parse dynamically if needed
          echo "super_linter_version=$version" >> $GITHUB_OUTPUT

      # Cache Super-Linter dependencies based on version
      - name: Cache Super-Linter dependencies
        id: cache-super-linter
        uses: actions/cache@v4
        with:
          path: ~/.cache/super-linter
          key: ${{ runner.os }}-super-linter-${{ steps.sl-version.outputs.super_linter_version }}
          restore-keys: |
            ${{ runner.os }}-super-linter-

      # Run Super-Linter
      - name: Super-Linter
        uses: super-linter/super-linter@v8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          DISABLE_ERRORS: true
          FILTER_REGEX_EXCLUDE: '^(?:dist|vendor|\.git|cache)/'
          FILTER_REGEX_INCLUDE: '.*\.(sh|bash|yaml|json|toml|md|py|css|js|editorconfig)$'
          LINTER_RULES_PATH: .

      # Commit and push automatic lint fixes on PRs
      - name: Commit and push linting fixes
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore: apply super-linter fixes"
          commit_user_name: "super-linter"
          commit_user_email: "super-linter@users.noreply.github.com"
