name: Linter
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    permissions:
        packages: read
        statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
          FILTER_REGEX_EXCLUDE: '^(?:dist|vendor|\.git|cache)/'
          FILTER_REGEX_INCLUDE: '.*\.(sh|bash|yaml|json|toml|md|py|css|js|editorconfig)$'
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          BASH_EXEC_IGNORE_LIBRARIES: true
          DISABLE_ERRORS: false
          FAIL_ON_CONFLICTING_TOOLS_ENABLED: true
          # LINTER_RULES_PATH: .
          # LINTER_RULES_PATH: .github/lint-configs

      - name: Commit and push linting fixes
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore: apply super-linter fixes"
          commit_user_name: "super-linter"
          commit_user_email: "super-linter@users.noreply.github.com"
