# https://github.com/marketplace/actions/update-git-submodules
name: Submodule update
on:
  workflow_dispatch:
  #schedule: [{cron: "0 0 * * 0"}]
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Update Submodules
        id: submodules
        uses: sgoudham/update-git-submodules@v2.1.3
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: update all submodules"
          branch: "feat/update-all-submodules"
          title: "feat: update all submodules"
          body: ${{ steps.submodules.outputs.prBody }}
