name: Submodule update
on:
  pull_request:
  workflow_dispatch:
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Update Submodules
        id: submodules
        uses: sgoudham/update-git-submodules@v2.1.3
        with:
        # The path to the '.gitmodules' file.
        # Defaults to '.gitmodules' in the root of the repository.
        gitmodulesPath: ""
        # The strategy to use when updating the submodules. Can be either 'commit' or 'tag'.
        # Defaults to 'commit'.
        strategy: "commit"
        # The git submodule(s) to update, the path should be the
        # same as the one specified in the '.gitmodules' file.
        # Defaults to all submodules in the '.gitmodules' file.
        submodules: ""

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: update all submodules"
          branch: "feat/update-all-submodules"
          title: "feat: update all submodules"
          body: ${{ steps.submodules.outputs.prBody }}
