# https://github.com/kehoecj/validate-configs-action
---
name: Lint Config Files

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
    paths:
      - "**/*.{yml,yaml,toml,json,ini,conf}"
      - ".editorconfig"
      - ".prettierrc*"
      - ".eslintrc*"
      - ".ruff.toml"
      - ".flake8"
  push:
    branches: [main, master]
    paths:
      - "**/*.{yml,yaml,toml,json,ini,conf}"
      - ".editorconfig"
      - ".prettierrc*"
      - ".eslintrc*"
      - ".ruff.toml"
      - ".flake8"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-and-fix:
    name: Validate and Fix Configs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Validate and Fix Config Files
        id: validate
        uses: kehoecj/validate-configs-action@v4.0.1
        with:
          group-by: "pass-fail"
          exclude-dirs: ".github,.git,.cache,go,node_modules,.var,.rustup,.wine,.zim,.void-editor"
          AUTO_FIX: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Fixes
        if: steps.validate.outcome == 'success' || steps.validate.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: auto-format and lint config files"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
